### ISSUE TITLE
Multiple ids

### ISSUE THREAD

**Issue by chilampoon** [reactome/ReactomeGraph4R#19]
Allow retrieving information for multiple ids, for example 
```
ids <- c("R-HSA-163200","R-HSA-1428517","R-HSA-611105","R-HSA-6799198", "R-HSA-72649", "R-HSA-72662")
somefunction(ids)
```
will return a dataframe
![image](https://user-images.githubusercontent.com/43943114/96289554-d93edd00-1017-11eb-9bf0-5e0285e9d6e4.png)

But it takes ~50 seconds to get the data for 1000 ids...

---
Also it's good to allow mapping multiple external ids to Reactome pathways, just like this [reactome.db](https://www.bioconductor.org/packages/devel/data/annotation/manuals/reactome.db/man/reactome.db.pdf) package:

```
gene1  pathway1 pathway2 pathway3
gene2  pathway1 pathway4 pathway5
gene3  pathway6
...
```

**Comment by cookersjs** [comment]
>But it takes ~50 seconds to get the data for 1000 ids...

I think that as long as their is some indication to the user that it is processing, then that is fine. Is the issue that it runs quickly with only one id at a time, but submitting multiple ids takes a _lot_ longer?

**Comment by chilampoon** [comment]
> > But it takes ~50 seconds to get the data for 1000 ids...
> 
> I think that as long as their is some indication to the user that it is processing, then that is fine. Is the issue that it runs quickly with only one id at a time, but submitting multiple ids takes a _lot_ longer?

I think it's fine actually...
