### ISSUE TITLE
Unable to knit Rmd file using current setup

### ISSUE THREAD

**Issue by cookersjs** [reactome/ReactomeGraph4R#22]
Hi there, when trying to knit the Rmd file I get a few errors where it can't locate the package or any of its contained methods. I made a bit of headway with this, but it will need to wait until tomorrow before I can work on this in earnest.

Error messages (from opening `vignettes/Introduction.Rmd` and pressing 'Knit' (which is what I did in ContentService package without issue):

```


processing file: Introduction.Rmd
  |.                                                                     |   2%
   inline R code fragments

  |...                                                                   |   4%
label: install (with options) 
List of 1
 $ eval: logi FALSE

  |....                                                                  |   6%
  ordinary text without R code

  |.....                                                                 |   8%
label: setup

Quitting from lines 41-42 (Introduction.Rmd) 
Error in library(ReactomeGraph4R) : 
  there is no package called 'ReactomeGraph4R'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
Execution halted
```

If I change line 41 to `library(reactome.graphdb4r)`, it seems to fix it, but then after I get the graph.db instance up and running and enter my credentials, another message pops up that says it can't find the `multiObjects.Rd` method. Strange - but I will look into this further tomorrow @chilampoon

**Comment by chilampoon** [comment]
Hmm, looks like you installed the package with the name `reactome.graphdb4r`, I think re-installing the package can resolve it: if you are in the `ReactomeGraph4R` project, then press the `Install & Restart` in the `Build` tab; or connect to the GraphDb neo4j local server first, then run this R command `devtools::install_github("reactome/ReactomeGraph4R", ref="develop")`

**Comment by cookersjs** [comment]
Thank you @chilampoon, your suggestion worked - I'll be posting the updated documentation shortly
